#!/bin/bash

#PJM -g gu14
#PJM -L rscgrp=share
#PJM -L gpu=1
#PJM -L elapse=47:00:00
#PJM --fs /work,/data
#PJM -N curriculumBO_SAM
#PJM -o curriculumBO_SAM.txt
#PJM -j
#PJM --mail-list suzuki-takahiro596@g.ecc.u-tokyo.ac.jp
#PJM -m b
#PJM -m e

module load cuda/11.1

cd "${PJM_O_WORKDIR}" || exit

#modify here
fold=2 #modify here. 5-fold CV.
pretrained="ImageNet" #'BigBbox' #"ImageNet"
metric="FAUC_Pretrained${pretrained}"
#for curriculumBO
curriStart='0.6' #'0.4' #'0.3' #'0.5' #'1.0' #ここ調整。
curriDecayRate='1.0' #'0.9' #DecayRate for curriculum


numIter=30 #4 #30 #4 #iteration for BO
numInfer=30 #how many images are generated by the simulator for inference
optimizer='SAM' #'SGD' #'Adam' #'VSGD' ###################################################要注意。ここ変えたので。

#for otimizers' epsilon
variability="0.05" #rho for SAM. default: 0.05. try 0.01
decayRate='1.0' #'0.9' #how much we decay the variability

numTrain=1000 #30 #512くらいでもいいかもね。
normalDir="/work/gk36/k77012/M2/data/NormalDir/" #データプールなら何でもよい。
normalIdList="/work/gk36/k77012/M2/normalFiles${numTrain}.csv"

numValid=200 #これも減らしてもいいかも
normalDir2="/work/gk36/k77012/M2/data/NormalDir/" #データプールなら何でもよい。
normalIdList2="/work/gk36/k77012/M2/normalFiles${numValid}.csv"

realValidPath='AllDataDir'
realValidBboxName="rare_small_bboxInfo_20_${fold}_withNormal"
realValidBbox="${realValidBboxName}.csv"
testPath='AllDataDir' #'AbnormalDir'
testBboxName="rare_small_bboxInfo_81_${fold}_withNormal"
testBbox="${testBboxName}.csv"

#for training
epoch=120 #40 #10 #40
batch_size=64
numSamples=50
model='SSD'

#make dir for model and log
modelPath="/work/jh170036a/k77012/M2/model/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/"
mkdir -p ${modelPath}
trainLog="/work/jh170036a/k77012/M2/train_log/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/"
mkdir -p ${trainLog}

bufText="/work/gk36/k77012/M2/buf_curriculumBO${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}_${fold}.txt" #use the same text as it is just a buffer
bestText="/work/gk36/k77012/M2/best_curriculumBO${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}_${fold}.txt"

#first, change directory
cd ../bo_io

for i in 1 2 3 4 5 6 7 8 9 10
do
  normalDirForInfer="/work/gk36/k77012/M2/data/NormalDir/"
  normalIdListForInfer="/work/gk36/k77012/M2/normalFiles${numInfer}.csv"

  boDir="/work/gk36/k77012/M2/bo_io/in/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}"
  mkdir -p ${boDir}
  boText="${boDir}/iter${i}.txt"

  #inference for the first 5 intial points
  for j in 1 2 3 4 5
  do
    abnormalDir="/work/gk36/k77012/M2/data/sim${j}_1000/"  #sim${j}_${numInfer}/" #大は小を兼ねる。1000枚のうち始めの３０枚を使用する。
    bboxPath="/work/gk36/k77012/M2/simDataInfo/bboxInfo/bboxInfo${j}_${numInfer}.csv"
    pipenv run python ../WisteriaCodes/initialInference.py $i $j ${abnormalDir} ${bboxPath} ${boText} ${modelPath} ${pretrained} ${curriStart} ${curriDecayRate} #i is used to identify the model to load, j is used to determine the X values. 結果をboTextに格納.
  done

  #inference for the next numIter points using BO module
  for j in $(seq 1 ${numIter}) #[1,numIter]
  do
    ./build/suggest --hm --ha --hpopt -a ei --md 5 --mi ${boText} >> ${bufText}  #run the BO module

    #save information
    abnormalDir="/work/jh170036a/k77012/M2/data/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/ver${i}/iter${j}_${numInfer}/"
    segMaskDir="/work/jh170036a/k77012/M2/SegmentationMask/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/ver${i}/mask${j}_${numInfer}/" #まあ無くてもよさそう
    paraDir="/work/jh170036a/k77012/M2/simDataInfo/paraInfo/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/ver${i}/"
    bboxDir="/work/jh170036a/k77012/M2/simDataInfo/bboxInfo/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/ver${i}/"
    paraPath="${paraDir}/parameterInfo${j}_${numInfer}.csv" #まあ無くてもよさそう
    bboxPath="${bboxDir}/bboxInfo${j}_${numInfer}.csv"

    mkdir -p ${abnormalDir} #train_${i}が作られていること前提ではない。親ディレクトリが無い場合は全て作る、＆、フォルダがすでに存在する場合は何もしない
    mkdir -p ${segMaskDir}
    mkdir -p ${paraDir}
    mkdir -p ${bboxDir}

    pipenv run python ../WisteriaCodes/fractalGenerator.py ${normalIdListForInfer} ${normalDirForInfer} ${abnormalDir} ${segMaskDir} ${paraPath} ${bboxPath} ${bufText} #bufText is used to know the X values.

    pipenv run python ../WisteriaCodes/inference.py $i ${bufText} ${abnormalDir} ${bboxPath} ${boText} ${modelPath} ${pretrained} ${curriStart} ${curriDecayRate} #i is used to identify the model to load, bufText is used to determine the X values. 結果をboTextに格納.

  done

  #bufferに出力するというよりかは、ここでboTextを基に、best値を判定し、buf同様の形式で出力すればよい。
  pipenv run python ../WisteriaCodes/findBest.py ${boText} >> ${bestText}

  ### generate training data
  #save information
  trainPath="ver${i}_${numTrain}"
  abnormalDir="/work/jh170036a/k77012/M2/data/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/${trainPath}/"
  segMaskDir="/work/jh170036a/k77012/M2/SegmentationMask/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/ver${i}_${numTrain}/"
  paraPath="/work/jh170036a/k77012/M2/simDataInfo/paraInfo/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/parameterInfo${i}_${numTrain}.csv"
  bboxPath="/work/jh170036a/k77012/M2/simDataInfo/bboxInfo/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/bboxInfo${i}_${numTrain}.csv"

  mkdir -p ${abnormalDir} #train_${i}が作られていること前提ではない。親ディレクトリが無い場合は全て作る、＆、フォルダがすでに存在する場合は何もしない
  mkdir -p ${segMaskDir}

  pipenv run python ../WisteriaCodes/fractalGenerator.py ${normalIdList} ${normalDir} ${abnormalDir} ${segMaskDir} ${paraPath} ${bboxPath} ${bestText} #bestText is used to know the X values.

  ### generate tvalidation data
  #save information
  validPath="ver${i}_${numValid}"
  abnormalDir2="/work/jh170036a/k77012/M2/data/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/${validPath}/"
  segMaskDir2="/work/jh170036a/k77012/M2/SegmentationMask/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/ver${i}_${numValid}/"
  paraPath2="/work/jh170036a/k77012/M2/simDataInfo/paraInfo/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/parameterInfo${i}_${numValid}.csv"
  bboxPath2="/work/jh170036a/k77012/M2/simDataInfo/bboxInfo/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/bboxInfo${i}_${numValid}.csv"

  mkdir -p ${abnormalDir2} #train_${i}が作られていること前提ではない。親ディレクトリが無い場合は全て作る、＆、フォルダがすでに存在する場合は何もしない
  mkdir -p ${segMaskDir2}

  pipenv run python ../WisteriaCodes/fractalGenerator.py ${normalIdList2} ${normalDir2} ${abnormalDir2} ${segMaskDir2} ${paraPath2} ${bboxPath2} ${bestText} #bestText is used to know the X values.

  savePath="/work/jh170036a/k77012/M2/result/curriculumBO/${realValidBboxName}/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}_variability${variability}_decay${decayRate}_t${numTrain}_v${numValid}_iter${numIter}_inf${numInfer}_epoch${epoch}/${trainPath}_valid${validPath}/${model}_batch${batch_size}_epoch${epoch}"
  mkdir -p ${savePath} #for saving Dir
  mkdir -p "${savePath}/train"
  mkdir -p "${savePath}/valid"
  mkdir -p "${savePath}/realValid"
  mkdir -p "${savePath}/test"

  #training the model
  pipenv run python ../WisteriaCodes/train_continual.py ${abnormalDir} ${abnormalDir2} ${realValidPath} ${testPath} ${bboxPath} ${bboxPath2} ${realValidBbox} ${testBbox} ${modelPath} ${model} ${epoch} ${batch_size} ${numSamples} ${i} ${savePath} ${optimizer} ${pretrained} ${variability} ${decayRate} >> ${trainLog}/model${i}_${trainPath}_${validPath}_${model}_epoch${epoch}_batchsize${batch_size}.txt
  echo $i'_finished'

done