#!/bin/bash

#PJM -g jh170036a
#PJM -L rscgrp=share
#PJM -L gpu=1
#PJM -L elapse=40:00:00
#PJM --fs /work,/data
#PJM -N minmin-training
#PJM -o minmin.txt
#PJM -j
#PJM --mail-list suzuki-takahiro596@g.ecc.u-tokyo.ac.jp
#PJM -m b
#PJM -m e

module load cuda/11.1

cd "${PJM_O_WORKDIR}" || exit

numIter=30 #4 #30 #4 #30 #4 #iteration for BO
numInfer=30 #how many images are generated by the simulator for inference
optimizer='Adam' #default
metric='Dice' #'IoU'

#for curriculumBO
curriStart='1.0' #'0.5'
curriDecayRate='0.9' #DecayRate for curriculum

bufText="/work/gk36/k77012/M2/buf_curriculumBO${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}.txt" #use the same text as it is just a buffer
bestText="/work/gk36/k77012/M2/best_curriculumBO${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}.txt"

numTrain=1000 #30 #1000 #30
normalDir="/work/gk36/k77012/M2/data/NormalDir${numTrain}/"
normalIdList="/work/gk36/k77012/M2/normalIdList${numTrain}.csv"

numValid=200
normalDir2="/work/gk36/k77012/M2/data/NormalDir${numValid}/"
normalIdList2="/work/gk36/k77012/M2/normalIdList${numValid}.csv"

realValidPath='AbnormalDir10' #real valid data as a few shot setting.
realValidBbox='abnormal10_bboxinfo.csv'
testPath='AbnormalDir' #'AbnormalDir5012'
testBbox='abnormal5870_bboxinfo.csv' #'abnormal5012_bboxinfo.csv'

#for training
epoch=40
batch_size=64
numSamples=50
model='SSD'

#make dir for model and log
modelPath="/work/gk36/k77012/M2/model/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/"
mkdir -p ${modelPath}
mkdir -p "/work/gk36/k77012/M2/train_log/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}"


#first, change directory
cd ../bo_io

for i in 1
do
  normalDirForInfer="/work/gk36/k77012/M2/data/NormalDir${numInfer}/"
  normalIdListForInfer="/work/gk36/k77012/M2/normalIdList${numInfer}.csv"

  boDir="/work/gk36/k77012/M2/bo_io/in/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}"
  mkdir -p ${boDir}
  boText="${boDir}/iter${i}.txt"

  #inference for the first 5 intial points
  for j in 1 2 3 4 5
  do
    abnormalDir="/work/gk36/k77012/M2/data/sim${j}_${numInfer}/"
    bboxPath="/work/gk36/k77012/M2/simDataInfo/bboxInfo/bboxInfo${j}_${numInfer}.csv"
    pipenv run python ../WisteriaCodes/initialInference.py $i $j ${abnormalDir} ${bboxPath} ${boText} ${modelPath} ${metric} ${curriStart} ${curriDecayRate} #i is used to identify the model to load, j is used to determine the X values. 結果をboTextに格納.
  done

  #inference for the next numIter points using BO module
  for j in $(seq 1 ${numIter}) #[1,numIter]
  do
    ./build/suggest --hm --ha --hpopt -a ei --md 7 --mi ${boText} >> ${bufText}  #run the BO module

    #save information
    abnormalDir="/work/gk36/k77012/M2/data/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/ver${i}/iter${j}_${numInfer}/"
    segMaskDir="/work/gk36/k77012/M2/SegmentationMask/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/ver${i}/mask${j}_${numInfer}/" #まあ無くてもよさそう
    paraDir="/work/gk36/k77012/M2/simDataInfo/paraInfo/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/ver${i}/"
    bboxDir="/work/gk36/k77012/M2/simDataInfo/bboxInfo/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/ver${i}/"
    paraPath="${paraDir}/parameterInfo${j}_${numInfer}.csv" #まあ無くてもよさそう
    bboxPath="${bboxDir}/bboxInfo${j}_${numInfer}.csv"

    mkdir -p ${abnormalDir} #train_${i}が作られていること前提ではない。親ディレクトリが無い場合は全て作る、＆、フォルダがすでに存在する場合は何もしない
    mkdir -p ${segMaskDir}
    mkdir -p ${paraDir}
    mkdir -p ${bboxDir}

    pipenv run python ../WisteriaCodes/fractalGenerator.py ${normalIdListForInfer} ${normalDirForInfer} ${abnormalDir} ${segMaskDir} ${paraPath} ${bboxPath} ${bufText} #bufText is used to know the X values.

    pipenv run python ../WisteriaCodes/inference.py $i ${bufText} ${abnormalDir} ${bboxPath} ${boText} ${modelPath} ${metric} ${curriStart} ${curriDecayRate} #i is used to identify the model to load, bufText is used to determine the X values. 結果をboTextに格納.

  done

  #bufferに出力するというよりかは、ここでboTextを基に、best値を判定し、buf同様の形式で出力すればよい。
  pipenv run python ../WisteriaCodes/findBest.py ${boText} >> ${bestText}

  ### generate training data
  #save information
  trainPath="ver${i}_${numTrain}"
  abnormalDir="/work/gk36/k77012/M2/data/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/${trainPath}/"
  segMaskDir="/work/gk36/k77012/M2/SegmentationMask/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/ver${i}_${numTrain}/"
  paraPath="/work/gk36/k77012/M2/simDataInfo/paraInfo/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/parameterInfo${i}_${numTrain}.csv"
  bboxPath="/work/gk36/k77012/M2/simDataInfo/bboxInfo/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/bboxInfo${i}_${numTrain}.csv"

  mkdir -p ${abnormalDir} #train_${i}が作られていること前提ではない。親ディレクトリが無い場合は全て作る、＆、フォルダがすでに存在する場合は何もしない
  mkdir -p ${segMaskDir}

  pipenv run python ../WisteriaCodes/fractalGenerator.py ${normalIdList} ${normalDir} ${abnormalDir} ${segMaskDir} ${paraPath} ${bboxPath} ${bestText} #bestText is used to know the X values.

  ### generate tvalidation data
  #save information
  validPath="ver${i}_${numValid}"
  abnormalDir2="/work/gk36/k77012/M2/data/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/${validPath}/"
  segMaskDir2="/work/gk36/k77012/M2/SegmentationMask/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/ver${i}_${numValid}/"
  paraPath2="/work/gk36/k77012/M2/simDataInfo/paraInfo/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/parameterInfo${i}_${numValid}.csv"
  bboxPath2="/work/gk36/k77012/M2/simDataInfo/bboxInfo/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/bboxInfo${i}_${numValid}.csv"

  mkdir -p ${abnormalDir2} #train_${i}が作られていること前提ではない。親ディレクトリが無い場合は全て作る、＆、フォルダがすでに存在する場合は何もしない
  mkdir -p ${segMaskDir2}

  pipenv run python ../WisteriaCodes/fractalGenerator.py ${normalIdList2} ${normalDir2} ${abnormalDir2} ${segMaskDir2} ${paraPath2} ${bboxPath2} ${bestText} #bestText is used to know the X values.

  savePath="curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/${trainPath}/${validPath}_test${testPath}/${model}_batch${batch_size}_epoch${epoch}"
  mkdir -p "/work/gk36/k77012/M2/result/${savePath}/" #for saving Dir
  mkdir -p "/work/gk36/k77012/M2/result/${savePath}/train"
  mkdir -p "/work/gk36/k77012/M2/result/${savePath}/valid"
  mkdir -p "/work/gk36/k77012/M2/result/${savePath}/realValid"
  mkdir -p "/work/gk36/k77012/M2/result/${savePath}/test"

  #training the model
  pipenv run python ../WisteriaCodes/train_continual.py ${abnormalDir} ${abnormalDir2} ${realValidPath} ${testPath} ${bboxPath} ${bboxPath2} ${realValidBbox} ${testBbox} ${modelPath} ${model} ${epoch} ${batch_size} ${numSamples} ${i} ${savePath} ${optimizer} ${metric} >> ../train_log/curriculumBO/start${curriStart}_decay${curriDecayRate}_${optimizer}_${metric}/model${i}_${trainPath}_${validPath}_${testPath}_${model}_epoch${epoch}_batchsize${batch_size}.txt
  echo $i'_finished'

done